server:
  port: 1243
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: contract-app
          uri: http://localhost:1242
          predicates:
            - Path=/api/contract/**
          filters:
            - RewritePath=/api/contract/(?<segment>.*), /${segment}