server:
  port: 1243
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: contract-app
          uri: http://localhost:1242
          predicates:
            - Path=/api/contract/**
          filters:
            - RewritePath=/api/contract/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: contractCircuitBreaker
                fallbackUri: forward:/fallback/contract
        - id: customer-app
          uri: http://localhost:1239
          predicates:
            - Path=/api/customer/**
          filters:
            - RewritePath=/api/customer/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: customerCircuitBreaker
                fallbackUri: forward:/fallback/customer
        - id: product-app
          uri: http://localhost:1240
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/product