name: Pull Request Analysis

on:
  pull_request:
    branches: [ "main" ]
    types: ["opened", "synchronize", "reopened"]

jobs:
  Continuous-PR-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean build